alter table "public"."shipment" drop constraint "shipment_consignee_fkey";

alter table "public"."shipment" drop constraint "shipment_status_fkey";

alter table "public"."pallet" alter column "id" drop default;

alter table "public"."pallet" alter column "id" add generated by default as identity;

alter table "public"."pallet" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."pallet" alter column "shipment_id" set data type bigint using "shipment_id"::bigint;

alter table "public"."pallet_scan" alter column "id" drop default;

alter table "public"."pallet_scan" alter column "id" add generated by default as identity;

alter table "public"."pallet_scan" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."pallet_scan" alter column "pallet_id" drop not null;

alter table "public"."pallet_scan" alter column "pallet_id" set data type bigint using "pallet_id"::bigint;

alter table "public"."project" alter column "id" drop default;

alter table "public"."project" alter column "id" add generated by default as identity;

alter table "public"."project" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."shipment" drop column "consignee";

alter table "public"."shipment" drop column "status";

alter table "public"."shipment" add column "consignee_id" bigint;

alter table "public"."shipment" add column "status_id" bigint not null;

alter table "public"."shipment" alter column "id" drop default;

alter table "public"."shipment" alter column "id" add generated by default as identity;

alter table "public"."shipment" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."shipment" alter column "project_id" drop not null;

alter table "public"."shipment" alter column "project_id" set data type bigint using "project_id"::bigint;

CREATE UNIQUE INDEX pallet_id_key ON public.pallet USING btree (id);

CREATE UNIQUE INDEX pallet_scan_id_key ON public.pallet_scan USING btree (id);

CREATE UNIQUE INDEX project_id_key ON public.project USING btree (id);

CREATE UNIQUE INDEX shipment_id_key ON public.shipment USING btree (id);

alter table "public"."pallet" add constraint "pallet_id_key" UNIQUE using index "pallet_id_key";

alter table "public"."pallet" add constraint "pallet_shipment_id_fkey" FOREIGN KEY (shipment_id) REFERENCES shipment(id) ON DELETE CASCADE not valid;

alter table "public"."pallet" validate constraint "pallet_shipment_id_fkey";

alter table "public"."pallet_scan" add constraint "pallet_scan_id_key" UNIQUE using index "pallet_scan_id_key";

alter table "public"."project" add constraint "project_id_key" UNIQUE using index "project_id_key";

alter table "public"."shipment" add constraint "shipment_consignee_id_fkey" FOREIGN KEY (consignee_id) REFERENCES consignee_partner(id) not valid;

alter table "public"."shipment" validate constraint "shipment_consignee_id_fkey";

alter table "public"."shipment" add constraint "shipment_id_key" UNIQUE using index "shipment_id_key";

alter table "public"."shipment" add constraint "shipment_status_id_fkey" FOREIGN KEY (status_id) REFERENCES shipment_status(id) not valid;

alter table "public"."shipment" validate constraint "shipment_status_id_fkey";



