create extension if not exists "postgis" with schema "extensions";


create table "public"."consignee_partner" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);

alter table "public"."consignee_partner" enable row level security;


create table "public"."country" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "code" text not null
);

alter table "public"."country" enable row level security;


create table "public"."donor" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);

alter table "public"."donor" enable row level security;


create table "public"."pallet" (
    "id" bigint generated by default as identity not null,
    "shipment_id" bigint not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);

alter table "public"."pallet" enable row level security;


create table "public"."pallet_scan" (
    "id" bigint generated by default as identity not null,
    "pallet_id" bigint,
    "location" geography not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);

alter table "public"."pallet_scan" enable row level security;


create table "public"."profile" (
    "id" uuid not null,
    "first_name" text,
    "last_name" text,
    "email" text
);

alter table "public"."profile" enable row level security;


create table "public"."profile_role" (
    "profile_id" uuid not null,
    "role_id" bigint not null
);

alter table "public"."profile_role" enable row level security;


create table "public"."project" (
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "name" text not null,
    "id" bigint generated by default as identity not null
);

alter table "public"."project" enable row level security;


create table "public"."role" (
    "id" bigint generated by default as identity not null,
    "role" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "public"."role" enable row level security;


create table "public"."shipment" (
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "origin_id" bigint not null,
    "destination_id" bigint not null,
    "donor_id" bigint,
    "bookkeeping_flexport" boolean,
    "bookkeeping_gik" boolean,
    "drive_link" text,
    "commercial_invoice_link" text,
    "estimated_delivery_date" timestamp with time zone,
    "flexport_tracking_id" text,
    "freight_tracking_id" text,
    "gik_value_amount_usd" numeric,
    "logistics_expense_donation_usd" numeric,
    "main_shipment_type_id" bigint,
    "weight_kg" numeric,
    "consignee_id" bigint,
    "impact_reporting" boolean,
    "patients_treated" numeric,
    "status_id" bigint not null,
    "id" bigint generated by default as identity not null,
    "project_id" bigint
);

alter table "public"."shipment" enable row level security;


create table "public"."shipment_manager" (
    "profile_id" uuid not null,
    "shipment_id" bigint not null
);

alter table "public"."shipment_manager" enable row level security;


create table "public"."shipment_status" (
    "id" bigint generated by default as identity not null,
    "status" text not null
);

alter table "public"."shipment_status" enable row level security;


create table "public"."shipment_type" (
    "id" bigint generated by default as identity not null,
    "shipment_type" text not null
);

alter table "public"."shipment_type" enable row level security;